---
- name: Verify apache installation
  hosts: managedNode
  become: yes
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
    - name: Ensure apache is at the latest version
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: Show a msg in in the terminal
      ansible.builtin.debug:
        msg: "Apache(httpd) installation and configuration is started"

    - name: Write the apache config file
      ansible.builtin.template:
        src: ../template/httpd.j2
        dest: /etc/httpd.conf
      notify:
        - Restart apache

    - name: Ensure apache is running
      ansible.builtin.service:
        name: httpd
        state: started

    - name: Show a msg in in the terminal
      ansible.builtin.debug:
        msg: "Apache(httpd) installation and configuration is Done"

  handlers:
    - name: Restart apache
      ansible.builtin.service:
        name: httpd
        state: restarted
